### ISSUE TITLE
Reload on submitting answer

### ISSUE THREAD

**Issue by Wittmaxi** [Talentrator/Prograchallenges.com#32]
**Describe the bug**
When I click on "submit" on answers, I need to reload the page in order to see my submission

**To Reproduce**
Go to a question, post an answer (all fields filled) click submit - see nothing being added

**Expected behavior**
Without reloading the page, I should instantly see my submission!

**Comment by aman2712** [comment]
https://watch.screencastify.com/v/wJUlDJnoKNjqwYAyGsIf

I don't think this is a real issue

**Comment by ShantanuLamba** [comment]
This is a real problem, I have experienced this

**Comment by aman2712** [comment]
> This is a real problem, I have experienced this

Maybe because of slow internet

**Comment by Wittmaxi** [comment]
Are we on the same branch? I was talking about the current build

**Comment by aman2712** [comment]
> Are we on the same branch? I was talking about the current build

I the current master branch has this issue fixed

**Comment by saransh-283** [comment]
Its fixed, check and respond
